# Generated by Django 6.0.1 on 2026-01-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary_range',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
